name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
        env:
          PIP_ROOT_USER_ACTION: ignore
