name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
       
      - name: Add missing utilities for setup-python
        run: |
          apt-get update
          apt-get install -y curl lsb-release
          apt-get install -y python3-distutils
          curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          rm get-pip.py

      - name: Check pip installation
        run: |
          echo "Checking pip3..."
          pip3 --version || echo "pip3 not found"
          which pip3 || echo "pip3 path not found"
      
          echo "Checking pip via python3..."
          python3 -m pip --version || echo "python3 -m pip not working"
          python3 -m site

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip

      - name: test
        run: ls -la
