name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
       
      - name: Install Python and pip
        run: |
          apt-get update
          apt-get install -y python3 python3-pip
      
      - name: Install lz4
        run: pip3 install lz4


      - name: test
        run: ls -la
