name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clear Python cache
        run: |
          sudo rm -rf /__t/Python
       
      - name: Add missing utilities for setup-python
        run: |
          apt-get update
          apt-get install -y curl lsb-release
     

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip

      - run: pip install lz4

      - name: test
        run: ls -la
