name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Install OS dependencies required for setup-python
        run: |
          apt-get update
          apt-get install -y \
            lsb-release \
            libnss3 \
            libxkbcommon0 \
            libffi-dev \
            libssl-dev \
            zlib1g \
            libbz2-1.0 \
            liblzma5 \
            libreadline-dev \
            libsqlite3-0 \
            libncursesw5 \
            libgdbm-compat4 \
            libuuid1 \
            curl \
            ca-certificates
             
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
          
      - run: pip install lz4

      - name: test
        run: ls -la
