name: Issue 1113

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
       
      - name: Add missing utilities for setup-python
        run: |
          apt-get update
          apt-get install -y curl lsb-release
          apt-get install -y python3-distutils
          curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          rm get-pip.py

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'


      - name: test
        run: ls -la
