name: 1128 testing

on:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat Pipfile
  
      - uses: gowridurgad/sample-python@main
      - run: cat Pipfile
    
     
      
