name: 783 error

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13,macos-14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Uninstall Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: Run Python 3.9
      run: python3.9 --version
