name: 783 error

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11,macos-12,macos-13]
       

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Uninstall Homebrew
    #   run: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
        
    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y gettext

      
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
      
    - name: Run Python3.10.13
      run: python --version
