name: 783 error

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
       

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Uninstall Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
        
    - name: Update and install gettext
      run: |
        sudo apk update
        sudo apk add gettext

      
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
      
    - name: Run Python3.10.13
      run: python --version
