name: Error 861 
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v4
    - name: Apt Update
      run: sudo apt-get update
    - name: Install lsb-release
      run: sudo apt-get install -y lsb-release
    - name: Set up python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
