name: PR 912 Test

on:
  workflow_dispatch:

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup-Python
      uses: priya-kinthali/setup-python@897-fix-iarna/toml
      with:
        python-version: '3.9'
