name: PyPy 3.10 Cache Issue

on:
  # schedule:
  #   - cron: "* * * * *" # Runs every 1 minute
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PyPy 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
        cache: pip

    - name: Create pip cache directory (Windows only)
      if: runner.os == 'Windows'
      run: if (-Not (Test-Path -Path "C:\Users\runneradmin\AppData\Local\pip\cache")) {mkdir -p C:\Users\runneradmin\AppData\Local\pip\cache}

    - name: Install dependencies
      run: |
        python -m ensurepip
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Print uv version
      run: |
        pip show uv
        
