name: error 972

on:
  schedule:
      - cron: "* * * * *" # Runs every 1 minute
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create pip cache directory
        run: mkdir -p C:\Users\runneradmin\AppData\Local\pip\cache
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip
