name: 903 error

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python with retry
      run: |
        n=0
        until [ "$n" -ge 5 ]
        do
          gh action run actions/setup-python@v5 --python-version '3.12.3' && echo "Setup Python succeeded on attempt $((n+1))" && break
          n=$((n+1))
          sleep 15
        done
