name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.19
      - name : purge numpy
        run: |
              python -m pip cache purge
      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
            python -m pip install numpy --ignore-installed
      - name: Print NumPy METADATA
        run: |
          python -c "import numpy; print(numpy.__file__)"
          # METADATA_PATH=$(python -c "import numpy; import os; print(os.path.join(os.path.dirname(numpy.__file__), 'numpy-*.dist-info', 'METADATA'))")
          # cat $METADATA_PATH
      - name: Print init.py
        run: cat /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/__init__.py
      - name: Check Python executable for pip freeze
        run: |
          which python
          python -m pip freeze | grep numpy
      
      - name: Check Python executable for python -c
        run: |
          which python
          python -c 'import numpy as np; print(np.__version__)'
