name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9.19


      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
      - name: uninstall
        run: pip uninstall numpy

      - name : purge numpy
        run: |
              python -m pip cache purge
      - name: Second command
        run: python -m pip install numpy --ignore-installed

              
      - name: Check Python executable for pip freeze
        run: |
          which python
          python -m pip freeze | grep numpy
      
      - name: Check Python executable for python -c
        run: |
          which python
          python -c 'import numpy as np; print(np.__version__)'

          
      # - name: list numpy
      #   run: |
      #     # python -m pip list | grep numpy
      #     # python -c "import numpy as np; print(np.__file__)"
      #     python -m pip show numpy
      #     # pip list | grep numpy
      #     # python -c "import sys; print(sys.path)"
      # # - name: find numpy
      # #   run: find / -name numpy
      # - name: grep numpy
      #   run: |
      #       pip list | grep numpy
      #       python -c "import numpy as np; print(np.__file__)"
      #       pip list
      #       python -m site
      #       echo $PYTHONPATH

      # - name: Run which python command in Python
      #   run: |
      #     python -c "import subprocess; result = subprocess.run(['which', 'python'], stdout=subprocess.PIPE); print(result.stdout.decode('utf-8'))"

      # - name: Run which pip command in Python
      #   run: |
      #     python -c "import subprocess; result = subprocess.run(['which', 'pip'], stdout=subprocess.PIPE); print(result.stdout.decode('utf-8'))"

      # - name: Check the numpy version
      #   run: |
      #     python -m pip freeze | grep numpy
          # python -c 'import numpy as np
          # python -c "import numpy as np; print('numpy version: ' + np.__version__)"  
