name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9.19
      - name : purge numpy
        run: |
              python -m pip cache purge

      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
            python -m pip cache purge
            python -m pip install numpy --ignore-installed

      - name: Check the numpy version
        run: |
          python -m pip freeze | grep numpy
          # python -c 'import numpy as np
          python -c "import numpy as np; print('numpy version: ' + np.__version__)"  
