name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.19
      - name : purge numpy
        run: |
              python -m pip cache purge
      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
            python -m pip install numpy --ignore-installed

      # - name: Print NumPy METADATA
      #   run: |
      #     METADATA_PATH=$(python -c "import numpy; import os; print(os.path.join(os.path.dirname(numpy.__file__), f'{numpy.__name__}-*.dist-info', 'METADATA'))")
      #     cat $METADATA_PATH
      - name: Print NumPy METADATA
        run: |
          METADATA_FILE=$(python -c "import numpy; import pkg_resources; print(pkg_resources.get_distribution('numpy').egg_info + '/METADATA')")
          echo "Printing METADATA:"
          cat "$METADATA_FILE"

      - name: Print NumPy PKG-INFO
        run: |
          PKG_INFO_FILE=$(python -c "import numpy; import pkg_resources; print(pkg_resources.get_distribution('numpy').egg_info + '/PKG-INFO')")
          echo "Printing PKG-INFO:"
          cat "$PKG_INFO_FILE" || echo "PKG-INFO file not found."
      - name: Print init.py
        run: cat /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/version.py
      - name: Print _version.py
        run: cat //opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/lib/_version.py
      # - name: Print gitversion.py
      #   run: cat /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy/_build_utils/gitversion.py

      - name: Install tree package
        run: sudo apt-get install -y tree
  
      - name: Print directory contents
        run: tree /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/numpy

      - name: Check Python executable for pip freeze
        run: |
          which python
          python -m pip freeze | grep numpy
      
      - name: Check Python executable for python -c
        run: |
          which python
          python -c 'import numpy as np; print(np.__version__)'
