name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9.19
      - name : purge numpy
        run: |
              python -m pip cache purge

      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
            python -m pip install numpy --ignore-installed
      - name: list numpy
        run: |
          python -m pip list | grep numpy
          python -c "import numpy as np; print(np.__file__)"
      - name: Run which python command in Python
        run: |
          python -c "import subprocess; result = subprocess.run(['which', 'python'], stdout=subprocess.PIPE); print(result.stdout.decode('utf-8'))"

      - name: Run which pip command in Python
        run: |
          python -c "import subprocess; result = subprocess.run(['which', 'pip'], stdout=subprocess.PIPE); print(result.stdout.decode('utf-8'))"

      - name: Check the numpy version
        run: |
          python -m pip freeze | grep numpy
          # python -c 'import numpy as np
          python -c "import numpy as np; print('numpy version: ' + np.__version__)"  
