name: 955 error

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.19
      - name : purge numpy
        run: |
              python -m pip cache purge
      - name: install requirments
        run: |
            python -m pip install numpy==1.26.4
            python -m pip install numpy --ignore-installed

      - name: Print init.py
        run: cat /path/to/numpy/version.py
      - name: Print _version.py
        run: cat /path/to/numpy/lib/_version.py
      - name: Print gitversion.py
        run: cat /path/to/numpy/_build_utils/gitversion.py
      - name: Check Python executable for pip freeze
        run: |
          which python
          python -m pip freeze | grep numpy
      
      - name: Check Python executable for python -c
        run: |
          which python
          python -c 'import numpy as np; print(np.__version__)'
