name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: mahabaleshwars/setup-python-main@main
      with:
        python-version-file: .tool-versions
