name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: mahabaleshwars/setup-python@feature/tool-version-file
      with:
        python-version: pypy3.7-v7.3.3rc1 
