name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      id: setuppy
      with:
        python-version: "3.8.0 - 3.10.0"
    - run: echo '${{ steps.setuppy.outputs.python-version }}'
