name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: elpic/setup-python@main
      with:
        python-version-file: .tool-versions
