name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    steps:
    - uses: actions/checkout@v4
    - uses: aparnajyothi-y/setup-python@tool-versions-regex
      with:
        python-version: python >=3.9 <3.14
