name: PR test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: elpic/setup-python@main
      with:
        python-version-file: .tool-versions
